# This workflow builds and pushes Docker images for the simulators that have
# been modified when a PR is done. 
# The first job detects the modified simulators. It inspects the repository to
# determine all the changed dockerfiles, using the github action changed-files.
# The second job uses the output of the first and runs with a matrix strategy,
# building and pushing the modified simulators to Docker Hub in parallel, each
# in its own job.
# If the running time of the workflow becomes a problem, it could be possible
# to incorporate caching of the Docker build process in the GitHub actions.
name: Build and push simulator Docker images
on:
  # On any PR we will save the docker images as -dev on docker hub
  pull_request:
  
  # When we merge into main we need to run this on push otherwise we would
  # never have the prod images on docker hub.
  push:
    branches:
      - main

jobs:
  generate-simulator-matrix:
    runs-on: ubuntu-latest
    outputs:
      simulator-dockerfile-paths: ${{ steps.changed-dockerfiles.outputs.all_changed_files }}

    steps:
      # fetch-depth is set to 2 to ensure that the two last commits are
      # available to the script that will generate the simulator matrix.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Example: https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-example.yml
      - name: Get all changed dockerfiles
        id: changed-dockerfiles
        uses: tj-actions/changed-files@v43
        with:
          matrix: true
          files: |
             simulators/**/*Dockerfile
      - name: Echo changed files
        run: |
          echo "all_changed_files=${{ steps.changed-dockerfiles.outputs.all_changed_files }}"

  publish-simulator-image:
    runs-on: ubuntu-latest
    needs: [generate-simulator-matrix]
    if: ${{ needs.generate-simulator-matrix.outputs.simulator-dockerfile-paths != '' && needs.generate-simulator-matrix.outputs.simulator-dockerfile-paths != '[]' }}
    strategy:
      # If building one simulator fails, continue with the others anyway.
      fail-fast: false

      matrix:
        simulator-dockerfile-path: ${{ fromJSON(needs.generate-simulator-matrix.outputs.simulator-dockerfile-paths) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get simulator name, version, directory and enviorment
        id: get
        run: | 
          : # Get Simulator name
          : # /some/path/to/simulator/version/Dockerfile -> simulator
          tmp=$(basename $(dirname $(dirname ${{ matrix.simulator-dockerfile-path }})))
          echo "simulator-name=$tmp" >> $GITHUB_OUTPUT

          : # Get Simulator version
          : # /some/path/to/simulator/version/Dockerfile -> version
          tmp=$(dirname ${{ matrix.simulator-dockerfile-path }})
          echo "simulator-version=$(basename $tmp)" >> $GITHUB_OUTPUT

          : # Get Simulation Directory
          echo "simulator-directory=$(dirname ${{ matrix.simulator-dockerfile-path }})" >> $GITHUB_OUTPUT

          : # Current enviorment 
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "enviorment=''" >> $GITHUB_OUTPUT
          else
            echo "enviorment=_dev" >> $GITHUB_OUTPUT
          fi

          cat $GITHUB_OUTPUT

      - name: Generate full image tag
        id: image-tag
        run: |
          echo "full_tag=${{ steps.get.outputs.simulator-name }}_${{ steps.get.outputs.simulator-version }}${{ steps.get.outputs.enviorment }}">> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.get.outputs.simulator-directory }}
          load: true
          file: ${{ matrix.simulator-dockerfile-path }}
          tags: |
             inductiva/kutu:${{ steps.image-tag.outputs.full_tag }}
      - name: Test
        run: |
          docker run --rm inductiva/kutu:${{ steps.image-tag.outputs.full_tag }} ./home/test_sim.sh
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            inductiva/kutu:${{ steps.image-tag.outputs.full_tag }}
          context: ${{ steps.get.outputs.simulator-directory }}
          file: ${{ matrix.simulator-dockerfile-path }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/inductiva/kutu
            maintainer=Inductiva Research Labs <contact@inductiva.ai>
            org.opencontainers.image.revision=$GITHUB_SHA
